const sliderData = [
  {
    id: 1,
    type: 'movie',
    title: 'البعبع',
    englishTitle: 'Al Baabaa',
    description: 'فيلم إثارة مشوق يحكي قصة رجل يواجه مخاوفه الداخلية في رحلة نفسية معقدة مليئة بالتشويق والغموض.',
    year: 2023,
    duration: '110 دقيقة',
    rating: 4.0,
    genre: 'إثارة',
    imageUrl: 'https://i.ytimg.com/vi/B6aUuyBP4_E/hq720.jpg?rs=AOn4CLDqtgej9xcQwWjechjj9H30pcBx9w&sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD',
    newRelease: true,
  },
  {
    id: 2,
    type: 'movie',
    title: 'عاصفة الصحراء',
    englishTitle: 'Desert Storm',
    description: 'فيلم أكشن ملحمي يتابع مجموعة من المحاربين في مهمة خطيرة عبر الصحراء لإنقاذ المدينة من الدمار.',
    year: 2022,
    duration: '130 دقيقة',
    rating: 4.5,
    genre: 'أكشن',
    imageUrl: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
    newRelease: false,
  },
  {
    id: 3,
    type: 'series',
    title: 'أسرار المدينة',
    englishTitle: 'City Secrets',
    description: 'مسلسل درامي مؤثر يكشف أسرار عائلة عريقة وصراعاتها الداخلية عبر ثلاثة أجيال في قلب المدينة القديمة.',
    year: 2021,
    seasons: 3,
    episodes: 30,
    rating: 4.2,
    genre: 'دراما',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2025&q=80',
    newRelease: true,
  },
  {
    id: 4,
    type: 'series',
    title: 'مقهى الأحلام',
    englishTitle: 'Dreams Cafe',
    description: 'مسلسل كوميدي دافئ يحكي قصص زوار مقهى صغير وكيف تتقاطع حياتهم بطرق مضحكة ومؤثرة.',
    year: 2023,
    seasons: 1,
    episodes: 10,
    rating: 3.8,
    genre: 'كوميديا',
    imageUrl: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2032&q=80',
    newRelease: false,
  },
];

export default sliderData;

